# Generated by Django 4.2.6 on 2023-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
