# Generated by Django 4.2.6 on 2023-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuenta_amount_cuenta_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
