# Generated by Django 4.2.6 on 2023-10-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_cuenta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
